---
- name: Ensure we are using apk
  ansible.builtin.fail:
    msg: "This role only supports {{ ansible_os_family }} systems that use apk as a package manager."
  when: ansible_pkg_mgr != "apk"

- name: Uninstall golang in apk
  block:
    - name: Update apk cache
      community.general.apk:
        update_cache: true
      changed_when: false # Cache update is a preparatory operation, not a state change
      become: true

    - name: Remove golang if it is installed
      community.general.apk:
        name: "{{ golang_distro_pkgs }}"
        state: absent
      become: true
